[build]
    publish = "dist/"

    functions = "serverless/"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/handlerequest"
  status = 200

[[redirects]]
  from = "/stream/*"
  to = "/.netlify/functions/stream"
  status = 200